image: ubuntu:24.04

stages:
  - create-vm
  - run-ansible

variables:
  YC_FOLDER_ID: b1gk2t60e1na1svr5mqs
  YC_CLOUD_ID: b1gb8fcs5t546hnkbn23
  IMAGE: ubuntu:24.04
  CPU: 2
  MEM: 4
  DISK_SIZE: 20
  VM_NAME: bookstore-app


before_script:
  - |
    apt update && apt install -y curl
    curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /usr/local/yc
    echo "$SA_KEY" > sa-key.json
    yc config profile create sa-profile || true
    yc config set folder-id ${YC_FOLDER_ID}
    yc config set cloud-id ${YC_CLOUD_ID}
    yc config set service-account-key sa-key.json
    yc config profile activate sa-profile

create:vm:
  stage: create-vm
  script:
    - |
      yc compute instance create \
        --name ${VM_NAME} \
        --zone ru-central1-b \
        --network-interface subnet-name=default-ru-central1-b,nat-ip-version=ipv4 \
        --create-boot-disk image-folder-id=standard-images,image-family=${IMAGE}, size=${DISK_SIZE} \
        --memory ${MEM} \
        --cores ${CPU} \
        --metadata-from-file user-data=infra/metadata.yaml
  tags:
    - all

wait:vm:
  stage: create-vm
  needs: ["create-vm"]
  script:
    - |
      eval "$(ssh-agent -s)"
      chmod 700 ~/.ssh
      echo "$SSH_KEY" | ssh-add -
      echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

      for i in $(seq 1 30); do
        STATUS=$(yc compute instance get --name ${VM_NAME} --format json | jq -r '.status')
        echo "Current status ${STATUS}"
        if [ "${STATUS}" == "RUNNING" ]; then
          break
        fi
        sleep 10
      done
      PUB_IP=$(yc compute instance get --name ${VM_NAME} --format json | jq -r '.network_interfaces[0].primary_v4_address.one_to_one_nat.address')
      echo "PUB_IP=$PUB_IP" > build.env
      for i in $(seq 1 30); do
        SSH_AV=$(ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 gitlab-runner@${PUB_IP} echo 1)
        if [ $SSH_AV == 1 ]; then
          echo "SSH is available"
          break
        fi
        sleep 5
      done
  artifacts:
    reports:
      dotenv: build.env
  tags:
   - all

run:ansible:
  stage: run-ansible
  trigger:
    include:
      - local: 'infra/run_ansible.yml'
  variables:
    HOST: $PUB_IP
    DRY_RUN: "false"
  rules:
    - when: on_success
